version: "3"
services:
  bot:
    build: ./bot
    container_name: cryptolab_bot
    env_file:
      - ./bot/.env
    networks:
      - mainNetwork
    depends_on:
      - postgres

  site:
    build: ./site
    container_name: cryptolab_site
    env_file:
      - ./site/.env
    ports:
      - "8000:8000"
    networks:
      - mainNetwork
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: crupto-lab_database
    environment:
      POSTGRES_USER: Allkriv
      POSTGRES_PASSWORD: AlphaAlphaTodes1209
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mainNetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - site
    networks:
      - mainNetwork

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot; sleep 60d; done;'"

volumes:
  postgres_data:


networks:
  mainNetwork:
    driver: bridge
