services:
  app:
    build: ./app
    depends_on:
      - postgres
    container_name: fastapi_app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - webnet

  postgres:
    image: postgres:15 # Используйте последнюю версию PostgreSQL
    container_name: postgres_db # Имя контейнера
    environment:
      POSTGRES_USER: myuser # Замените на имя пользователя, которое хотите использовать
      POSTGRES_PASSWORD: mypassword # Замените на пароль
      POSTGRES_DB: mydatabase # Замените на имя базы данных
    ports:
      - "5432:5432" # Порт, на котором будет доступен PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Для постоянного хранения данных
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - webnet

networks:
  webnet:


volumes:
  postgres_data:
