services:
  app:
    build: ./app
    depends_on:
      - postgres
    container_name: fastapi_app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - webnet

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - webnet

  telegram_bot:
    build: ./bot
    depends_on:
      - localtunnel
    networks:
      - webnet

  localtunnel:
    build:
      context: ./localtunnel
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    networks:
      - webnet

networks:
  webnet:


volumes:
  postgres_data:
