# Generated by Django 5.0.6 on 2024-06-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_user_userip_delete_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserIP',
        ),
    ]
