# Generated by Django 5.0.6 on 2024-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_remove_user_balance_user_tokens_delete_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy_recovery_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='max_energy',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='mining_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
