# Generated by Django 5.0.6 on 2024-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_user_energy_recovery_speed_user_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tokens',
            new_name='dust',
        ),
        migrations.RemoveField(
            model_name='user',
            name='energy_recovery_speed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mining_speed',
        ),
        migrations.AddField(
            model_name='user',
            name='current_energy',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
