# Generated by Django 5.0.6 on 2024-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_rename_tokens_user_dust_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dust',
            new_name='tokens',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_energy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_energy',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
